---
title: "Pruebas consulta popular"
author: "M. Anzarut, F. González, T. Ortiz"
date: "2/12/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(quickcountmx)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
computos_tbl <-
  read_delim(
    "../datos/20210802-2130_INE-CONSULTA-POPULAR-2021/20210802-2130_COMPUTOS-INE-CP2021.csv",
    delim = "|", skip = 6)  |>
  mutate(ln = LISTA_NOMINAL_MRCP) |>
  mutate(ESTRATO = paste0(stringr::str_pad(ID_ENTIDAD, 2, pad = "0"),
                          stringr::str_pad(ID_DISTRITO_FEDERAL, 2, pad = "0")))
resultados_finales <- computos_tbl |> 
  select(CLAVE_MRCP, all_of(c("OPINION_SI", "OPINION_NO", "NULOS"))) |> 
  pivot_longer(all_of(c("OPINION_SI", "OPINION_NO", "NULOS"))) |> 
  group_by(name) |> 
  summarise(suma = sum(value)) |> 
  mutate(pct_obs = 100 * suma / sum(suma)) |> 
  rename(party = name)
muestras <- read_csv("../salida/muestras_cp_2021.csv")
muestras_cont <- read_csv("../salida/muestras_contaminadas_cp_2021.csv")
```

## Cobertura razón bootstrap

```{r}
estratos_tbl <- computos_tbl |> group_by(ESTRATO) |> count()
estratos_tbl
```

```{r}
library(furrr)
plan(multisession, workers = 8)
```


```{r}
resultados_tbl <- future_map_dfr(1:250, function(num){
  muestra <- muestras |> filter(num_muestra == num)
  res <- quickcountmx::ratio_estimation(muestra,
    stratum = ESTRATO, data_stratum = estratos_tbl, n_stratum = n, 
    parties = any_of(c("OPINION_SI", "OPINION_NO", "NULOS")), B = 150)
  res$num_muestra <- num
  res
}, .options = furrr_options(seed = TRUE))
```

```{r, fig.width = 6, fig.height=3}
resultados_tbl |> ggplot(aes(x = prop)) + geom_histogram() +
  facet_wrap(~ party, scales = "free_x") +
  geom_vline(data = resultados_finales, aes(xintercept = pct_obs), colour = "red")
```

```{r, fig.width = 10, fig.height=3}
resultados_tbl |> ggplot(aes(x = num_muestra, ymin = prop - 2*std_error, ymax = prop + 2*std_error)) +
  geom_linerange() +
  facet_wrap(~ party, scales = "free_y") + 
  geom_hline(data = resultados_finales, aes(yintercept = pct_obs), colour = "red")

```
```{r}
resultados_tbl |> left_join(resultados_finales) |> 
  mutate(cubre = (pct_obs >= prop - 2 * std_error) & (pct_obs <= prop + 2 * std_error)) |> 
  group_by(party) |> 
  summarise(cobertura = mean(cubre))
```

```{r}
resultados_tbl <- future_map_dfr(1:250, function(num){
  muestra <- muestras_cont |> filter(num_muestra == num)
  res <- quickcountmx::ratio_estimation(muestra,
    stratum = ESTRATO, data_stratum = estratos_tbl, n_stratum = n, 
    parties = any_of(c("OPINION_SI", "OPINION_NO", "NULOS")), B = 150)
  res$num_muestra <- num
  res
}, .options = furrr_options(seed = TRUE))
```

```{r, fig.width = 6, fig.height=3}
resultados_tbl |> ggplot(aes(x = prop)) + geom_histogram() +
  facet_wrap(~ party, scales = "free_x") +
  geom_vline(data = resultados_finales, aes(xintercept = pct_obs), colour = "red")
```

```{r, fig.width = 10, fig.height=3}
resultados_tbl |> ggplot(aes(x = num_muestra, ymin = prop - 2*std_error, ymax = prop + 2*std_error)) +
  geom_linerange() +
  facet_wrap(~ party, scales = "free_y") + 
  geom_hline(data = resultados_finales, aes(yintercept = pct_obs), colour = "red")

```
```{r}
resultados_tbl |> left_join(resultados_finales) |> 
  mutate(cubre = (pct_obs >= prop - 2 * std_error) & (pct_obs <= prop + 2 * std_error)) |> 
  group_by(party) |> 
  summarise(cobertura = mean(cubre))
```


